# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: AzureResourceName
    default: "namespace-backend"
    displayName: "Pipeline Name"
    type: string
  - name: Company
    default: "namespace"
    displayName: "Company Name"
    type: string
    values:
      - namespace
  - name: AWSRegion
    default: "ap-southeast-1"
    displayName: "AWS Region"
    type: string
  - name: awsRegionShortName
    default: "sea1"
    displayName: "AWS Region Short Name"
    type: string
  - name: AppName
    default: "namespace-backend"
    displayName: "App Name"
    type: string

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: S3Download@1
  inputs:
    awsCredentials: 'jun7861-namespace-connection001'
    regionName: 'ap-southeast-1'
    bucketName: 'jun7861-namespace-bucket'
    sourceFolder: '$(System.DefaultWorkingDirectory)/xsd'
    globExpressions: '*.xsd'
    targetFolder: '$(System.DefaultWorkingDirectory)/xsd'

# - task: LambdaDeployFunction@1
#   inputs:
#     awsCredentials: 'jun7861-namespace-connection001'
#     regionName: 'ap-southeast-1'
#     deploymentMode: 'codeonly'
#     functionName: '${{ parameters.Company }}-${{ parameters.AppName }}-${{ parameters.awsRegionShortName }}-namespace-downloadConfiguration'
#     codeLocation: 's3object'
#     s3Bucket: '${{ parameters.Company }}-${{ parameters.AppName }}-${{ parameters.awsRegionShortName }}-s3-source-code'
#     s3ObjectKey: 'functions/namespace-backend.zip'