service: project-power-diesel
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  validateXML:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /landing
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
